language: node_js
node_js:
  - '8'

services:
  - mongodb

branches:
  only:
    - master
env:
  global:
    - NODE_ENV=test
    - OPE_PORT=3000
    - secure: ng3Yz5vGtI+hUTLUQ+AFVrgkAmqJ/4ADc9DsEfeN2YXWtPt9WATCth05nBb3pKc6L2Y1Kn9MT9GuyR/XBszOUYG+bNq1ADCntqYL+d5qaG6YKM5bGlMJz8DXVickFWJmMT4Cq8DR3dOiqe+ibu1MY2J1yVYX7YGy67EHXoyJhxALpdSqR0WCyp3dm6HA4anMcPzkD6T+TnxYzWDqHp2RqSa/N4NJOAplWPgmuMTyN6IEMCfQT755ZZGTxXi35hzzEnzBvHZVKH/ITdv2h2coSFsLVFixC3uOCy+L35VpadmgpnWzX+tSZBm869ywiZzDd4dIGMgn+huwzO7QFLBZ2q7xVD4tnDfESGAEOr7EMfF9kB+LpN1Zzv/fU4KCm9XG5MKPnFlPIjleNE8LV0V/fgvgqGcIKiz8bKS9LqkNP60YWZiXGaSUJS+IRKzBvlpHNAUDd4yjInB/iCEjlBZhR8ex/GgU002lyKUSzfsfdQJhhxV3xuvPopMS+36ZxE7Elo2xz6eod4ObbTSuqgfPMeUTn1Nx4KFEsdrepo9sQLbIGYKuZ0ccTJsuK21FpnCXbxuziaButCN7NKVXI+woaoLcNfMn+oWUQCmT8E2u8PVCy3+XAAnWn4d45OFA1ZdRttW/T38vozOTdPVcz7OQPX80JbmekMUVL9g3SiOfYu4=

script:
  - npm start &
  - npx wait-on http://localhost:3000
  - npm test
  - npm install -g @th-koeln/graphql-docs
  - mkdir docs/
  - graphql-docs-gen http://localhost:3000/graphql docs/index.html

deploy:
  provider: pages
  local-dir: docs/
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
